plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'de.bacherik'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

shadowJar {
    archiveBaseName.set('DisKube')
    archiveClassifier.set('')
    archiveVersion.set('')

    manifest {
        attributes('Main-Class': 'de.bacherik.Main', "Multi-Release": true)
    }
}

dependencies {
    // https://mvnrepository.com/artifact/net.dv8tion/JDA
    implementation("net.dv8tion:JDA:5.5.0")
    implementation("ch.qos.logback:logback-classic:1.6.4")
    // https://mvnrepository.com/artifact/io.kubernetes/client-java
    implementation("io.kubernetes:client-java:23.0.0")

    testImplementation platform('org.junit:junit-bom:5.12.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}
